<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormState;

/**
 * Implements hook_help().
 */
function sipos_hello_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.sipos_hello':
      $out = '';
      $out .= '<h3>' . t('A boot :))') . '</h3>';
      $out .= '<p>' . t('Dees is een veurbiejld modoele.') . '</p>';
      return $out;

    default:
  }
}

/**
 * Implements hook_form_alter().

  function sipos_hello_form_alter(&$form, $form_state, $form_id) {
    if ($form_id == 'salutation_configuration_form') {
      $form['salutation']['#default_value'] .= ' FORM ALTERED';
    }
  }
 */


/* EVEN BETTER */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sipos_hello_form_salutation_configuration_form_alter(&$form, $form_state, $form_id) {
  $form['salutation']['#default_value'] .= ' FORM ALTERED';
}

/**
 * Implements hook_mail().
 */
function sipos_hello_mail($key, &$message, $params) {
  switch ($key) {
    case 'sipos_hello_log':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('There is an error on your website');
      $message['body'][] = $params['message'];
      break;
  }
}

/**
 * Implements hook_mail_alter().
 */
function sipos_hello_mail_alter(&$message) {
  switch ($message['key']) {
    case 'sipos_hello_log':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      break;
  }
}
