<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sipos_hello_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.sipos_hello':
      $out = '';
      $out .= '<h3>' . t('A boot :))') . '</h3>';
      $out .= '<p>' . t('Dees is een veurbiejld modoele.') . '</p>';
      return $out;
      
    default:
  }
}