<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormState;

/**
 * Implements hook_help().
 */
function sipos_hello_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.sipos_hello':
      $out = '';
      $out .= '<h3>' . t('A boot :))') . '</h3>';
      $out .= '<p>' . t('Dees is een veurbiejld modoele.') . '</p>';
      return $out;

    default:
  }
}

/**
 * Implements hook_form_alter().

  function sipos_hello_form_alter(&$form, $form_state, $form_id) {
    if ($form_id == 'salutation_configuration_form') {
      $form['salutation']['#default_value'] .= ' FORM ALTERED';
    }
  }
 */


/* EVEN BETTER */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sipos_hello_form_salutation_configuration_form_alter(&$form, $form_state, $form_id) {
  $form['salutation']['#default_value'] .= ' FORM ALTERED';
}

/**
 * Implements hook_mail().
 */
function sipos_hello_mail($key, &$message, $params) {
  switch ($key) {
    case 'sipos_hello_log':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('There is an error on your website');
      $message['body'][] = $params['message'];
      
      /* TOKENS */
      $user_message = 'De aanGemeld3 gebru1ker IS: [current-user:name].';
      $message['body'][] = \Drupal::token()->replace($user_message, ['current-user' => \Drupal::currentUser()]);
      /* TOKENS */
      
      break;
  }
}

/**
 * Implements hook_mail_alter().
 */
function sipos_hello_mail_alter(&$message) {
  switch ($message['key']) {
    case 'sipos_hello_log':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      break;
  }
}

/**
 * Implements hook_token_info().
 */
function sipos_hello_token_info() {
  $type = [
    'name' => t('Sipos Hello'),
    'description' => t('Tokens related to Sipos Hello module'),
  ];
  
  $tokens['salutation'] = [
    'name' => t('Salutation'),
    'description' => t('The Sipos Hello salutation value.'),
  ];
  
  return [
    'types' => ['sipos_hello' => $type],
    'tokens' => ['sipos_hello' => $tokens],
  ];
}

/**
 * Implements hook_tokens().
 */
function sipos_hello_tokens($type, $tokens, array $data, array $options, \Drupal\Core\Render\BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if ($type == 'sipos_hello') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'salutation':
          $replacements[$original] = \Drupal::service('sipos_hello.salutation')->getSalutation();
          $config = \Drupal::config('sipos_hello.custom_salutation');
          $bubbleable_metadata->addCacheableDependency($config);
          break;
      }
    }
  }
  return $replacements;
}

/**
 * Implements hook_theme().
 */
function sipos_hello_theme($existing, $type, $theme, $path) {
  return [
    'sipos_hello_salutation' => [
      // template with the name sipos-hello-salutation.html.twig inside the /templates
      //folder of our module
      'variables' => ['salutation' => NULL, 'target' => NULL, 'overridden'
        => FALSE],
    ],
  ];
}

/**
 * Default preprocessor function for the sipos_hello_salutation theme hook.
 */
function template_preprocess_sipos_hello_salutation(&$variables) {
  $variables['attributes'] = [
    'class' => ['salutation'],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function sipos_hello_theme_suggestions_sipos_hello_salutation($variables) {
  $suggestions = [];
  if ($variables['overridden'] == TRUE) {
    $suggestions[] = 'sipos_hello_salutation__overridden';
  }
  return $suggestions;
}


/** Include css library only in sipos_hello pages **/

/**
 * Implements hook_page_attachments().
 */
function sipos_hello_page_attachments(&$attachments) {
  $path = \Drupal::service('path.current')->getPath();
  if ($path == '/sipos/hello') {
    $attachments['#attached']['library'][] = 'sipos_hello/sipos-library';
  }
}