<?php

/*
 * Implements hook_theme().
 */

function oef_raadgetal_theme($existing, $type, $theme, $path) {
  $theme = [
    'oef_raadgetal_basis_template' => [
      'render element' => 'build',
      'template' => 'oef_raadgetal_basis_template',
    ],
    'oef_raadgetal_start_pagina' => [
      'render element' => 'build',
      'template' => 'oef_raadgetal_start_raden'
    ],
    'oef_raadgetal_raad_form' => [
      'render element' => 'form',
    ]
  ];
  
  return $theme;
}
