<?php

use Drupal\user\Entity\User;
use Drupal\node\Entity\Node;
use Drupal\file\Entity\File;

function hello_hello_world() {
  return '<div class="container">' . t('Hello Drupal 8 waka waka') . '</div>';
}

function hello_welcome() {
  $user = User::load(\Drupal::currentUser()->id());
  if ($user->get('uid')->value < 1) {
    return '<div class="container">' . t('Welcome stranger') . '</div>';
  }
  else {
    return '<div class="container">' . t("Welcome " . $user->getUsername() . "!") . '</div>';
  }
}

function hello_create_node() {
  // The node entity bundle
  $node = Node::create([
        'type' => 'article',
        'langcode' => 'en',
        'created' => REQUEST_TIME,
        'changed' => REQUEST_TIME,
        'uid' => 1,
        'title' => 'My test!',
        // An array with taxonomy terms
        'field_tags' => [1],
        'body' => [
          'summary' => '',
          'value' => '<p>The body of the node</p>',
          'format' => 'full_html',
        ],
  ]);
  $node->save();
  \Drupal::service('path.alias_storage')->save("/node/$node->id()", "/hello/learning/example-node", "en");
  
  $node_es = $node->addTranslation('es');
  $node_es->title = 'Mi prueba!';
  $node_es->body->value = '<p>El cuerpo de mi nodo.</p>';
  $node_es->body_format = 'full_html';  
  $node_es->save();
  \Drupal::service('path.alias_storage')->save("/node/$node->id()", "/mi/ruta", "es");
}

function hello_create_file() {
  $file = File::create([
    'uid' => 1,
    'filename' => 'logo.png',
    'uri' => 'public://page/logo.png',
    'status' => 1,
  ]);
  $file->save();
  return t("File was created !!!");
}

function hello_create_node_with_file() {
  $node = Node::create([
    'type' => 'article',
    'langcode' => 'en',
    'created' => REQUEST_TIME,
    'changed' => REQUEST_TIME,
    'uid' => 1,
    'title' => 'My title',
    'field_tags' => [2],
    'body' => [
      'summary' => 'There is a node with a file being created.',
      'value' => 'My node!',
      'format' => 'full_html',
    ],
    'field_image' => [
      'target_id' => 1,
      'alt' => "My 'alt'",
      'title' => "Mamahue"
    ],
  ]);
  $node->save();
  \Drupal::service('path.alias_storage')->save("/node/$node->id", '/learning/hello/nodewithfile', 'en');
}
