<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/*
 * Implements hook_help().
 */

function d8md_hello_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.d8md_hello':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is an example') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_form_FORM_ID_alter(). */
function d8md_hello_form_hi_config_form_alter(&$form, FormStateInterface $form_state, $form_id) {
// Perform  alterations . 
  $form['#submit'][] = 'd8md_hello_hi_conf_form_submit';
}

/**
 * Custom submit handler for the form_salutation_configuration form.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function d8md_hello_hi_conf_form_submit(&$form, FormStateInterface $form_state) {
  $teste = 'Mi-hoen';
  var_dump($teste);
}
